### ISSUE TITLE
Allow setting of local HTTP server address and port

### ISSUE THREAD

**Issue by moggers87** [moggers87/exhibition#73]
Currently this is hard coded to `http://localhost:8000`

This should be a set of arguments for the `serve` subcommand.

**Comment by JordanLozinski** [comment]
Options or arguments? As options we could have them default to localhost and 8000 respectively.

**Comment by JordanLozinski** [comment]
#74

**Comment by JordanLozinski** [comment]
Please look again at my branch. (Am I supposed to make a new pull request after revisions?) I'm passing the existing tests as well as the test logic I added.

**Comment by moggers87** [comment]
You can push (or force push) to the same branch and it will update the pull request automatically.

I've had a quick skim read of your new changes and it looks fine. I'll have a proper read tomorrow morning :smiley_cat:
